import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Captur Photography"
        message="Capture moments in
       nature to keep them alive."
      />
      <Slider slides={SliderData} />
      <Instagram />
      <div className="relative bottom-[-18rem]">
        <Footer />
      </div>
    </div>
  );
}
